### ISSUE TITLE
Save/Load examples

### ISSUE THREAD

**Issue by ottothecow** [brendanjodowd/SAS-R#1]
I love your cheat sheet for introducing SAS users to R, but I'd make one suggestion:

In the File operations suggestion, I believe you should replace the save()/load() examples with saveRDS() and readRDS()

The *RDS functions are functionally equivalent to setting SAS data into/from a library--they store a single object and they let you easily define a name on load.

Generally using save() is a bad habit, especially when sharing data with others and only saving a single dataframe.  It can be useful in certain circumstances (e.g. saving many pieces of an environment for resumption later) but I'd say that's beyond the scope of a new-user cheat sheet.

Load() can be particularly dangerous since it will overwrite existing objects without warning.  It can be potentially catastrophic to perform a plain load() on a file created by another team member.  Especially for SAS users who may be new to concepts like environments, variable scopes, and the existence of variables/objects beyond dataframes.  Much better to use loadRDS() where you can pick and choose which objects you actually want to load and assign them non-conflicting names.

**Comment by brendanjodowd** [comment]
Hi! Thanks for your feedback. I had not heard of saveRDS and readRDS before now, but can see how they would be more relatable to a SAS user, and I like how you can load files into a newly named object. I have updated the cheatsheet using those functions and created a pull request. Please let me know if you have any other nice ideas!
Thanks,
Brendan
